mongo_db_url:  mongodb+srv://hake:hake@cluster2.o40doow.mongodb.net/test
mongo_cluster_name: testebemgay
mask_link: false
mask: https://discord.gg/impulso
dm_reaction: false
dm_pin: false
dm_typing: true
dm_reply: true
dm_cooldown: 67
event_message: true 
event_voice: true
reactions: 
 - â¤ï¸
 - ğŸ˜˜
 - ğŸ˜
 - ğŸ’“
 - ğŸ’–
 - ğŸ¥°

reply_messages: 
 - Desculpa o incomodo anjo :')
 - Eu nem me apresentei nÃ© kk
 - Prazer sou sua nova amiguinha, fofo(a)
 - Que tal, sermos amigos? seria uma boa ideia certo?
 - Vem me ver em call, jogar e se divertir, favorzin rs
 - Se gostar do nosso servidor, poderia atÃ© estar aderindo a staff?
 - Deixaria a amguinha muito feliz, rs kk
 - Foi um prazer conhece-lo(a), gute gute ...
 - Te espero lÃ¡ amorzinho, junto com minhas amigas ...
 
